substitutions:
  _REGION: asia-northeast1
  _SERVICE: akb-weekly-dashboard

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/akb-dashboard/${_SERVICE}:$SHORT_SHA
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/akb-dashboard/${_SERVICE}:$SHORT_SHA
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/akb-dashboard/${_SERVICE}:$SHORT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --max-instances=2
      - --memory=256Mi

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/akb-dashboard/${_SERVICE}:$SHORT_SHA
